id: IE33B3090
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T01:37:22+00:00'
last_modified: '2022-06-08T02:49:55.051841+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD45150
  title: གསུང་འབུམ། ཚོགས་དྲུག་རང་གྲོལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    BDD8:
      image_group_id: I2DB57571
      title: ''
      total_pages: 1128
      order: 1
      base_file: BDD8.txt
    '5725':
      image_group_id: I2DB57572
      title: ''
      total_pages: 708
      order: 2
      base_file: 5725.txt
    1AD7:
      image_group_id: I2DB57573
      title: ''
      total_pages: 824
      order: 3
      base_file: 1AD7.txt
    BF08:
      image_group_id: I2DB57574
      title: ''
      total_pages: 850
      order: 4
      base_file: BF08.txt
    CB71:
      image_group_id: I2DB57575
      title: ''
      total_pages: 662
      order: 5
      base_file: CB71.txt
    41FC:
      image_group_id: I2DB57576
      title: ''
      total_pages: 722
      order: 6
      base_file: 41FC.txt
    '8146':
      image_group_id: I2DB57577
      title: ''
      total_pages: 704
      order: 7
      base_file: 8146.txt
    BA78:
      image_group_id: I2DB57578
      title: ''
      total_pages: 692
      order: 8
      base_file: BA78.txt
    9DDC:
      image_group_id: I2DB57579
      title: ''
      total_pages: 710
      order: 9
      base_file: 9DDC.txt
    '9803':
      image_group_id: I2DB57580
      title: ''
      total_pages: 594
      order: 10
      base_file: 9803.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
